### ISSUE TITLE
你好,使用你的DEMO,文件可以正常上传,但是上传完成后合并的文件是0字节

### ISSUE THREAD

**Issue by FirYuen** [sunhaikuo/uploadDemo#3]
我这边的环境是node v8.9.3 npm 5.6.0 成功运行后上传文件可以分割上传,但是无法合并文件,请问我这边出问题的可能情况是?

$ node upload.js
服务启动完成，端口监听5000！
nodeServer\uploads\cb9665bbf1999e8e513b8df8fb71be88
cb9665bbf1999e8e513b8df8fb71be88 疯狂Java讲义  第3版 PDF电子书下载 带书签目录 完整版.pdf
(node:13744) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of undefin
ed
(node:13744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled wi
ll terminate the Node.js process with a non-zero exit code.

**Comment by zhuyinjing** [comment]
我也遇到了这个问题，合并后的文件在/uploads文件夹下，文件的大小为0，而且是txt文本格式。

**Comment by sunhaikuo** [comment]
已解决, 启动时, 重新yarn install, 新增加了包
